name: Java CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [7, 8]

    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build with Maven
        run: >
          mvn install 
          --define "skipTests=true" 
          --define "mavin.javadoc.skip=true" 
          --batch-mode 
          --show-version 
          --file duo-client/pom.xml
      - name: Test with Maven
        run: >
          mvn test 
          --batch-mode 
          -file duo-client/pom.xml
